# Generated by Django 4.2.11 on 2026-05-04 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_galleryimage_service_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential Cleaning'), ('Commercial', 'Commercial Cleaning'), ('Specialty', 'Specialty Cleaning')], default='Residential', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(help_text='FontAwesome class, e.g., fas fa-spray-can-sparkles', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_start',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
