# Generated by Django 4.2.11 on 2026-05-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_galleryimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(default='General Cleaning', max_length=100),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
