# Generated by Django 4.2.11 on 2026-05-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_quoterequest_phone_quoterequest_service_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
