# Generated by Django 4.2.11 on 2026-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
