# Generated by Django 4.2.11 on 2026-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_quoterequest_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
